### ISSUE TITLE
Inclusion in Stitch?

### ISSUE THREAD

**Issue by chrisgoddard** [singer-io/tap-doubleclick-campaign-manager#8]
I'm wondering if there are any plans to include this Tap in Stitch in the near future?

**Comment by briansloane** [comment]
Hi @chrisgoddard. This is available in Stitch for all customers under the name Campaign Manager since Google [formally renamed the product](https://support.google.com/dcm/answer/9015629?hl=en) last year.

**Comment by chrisgoddard** [comment]
I was literally just coming back to delete this! I just saw it. Sorry about that. Thanks :)
